language: python
python:
- '3.7'

services:
  - docker

before_install:
  - ls
install:
  - ls
before_script:
  - docker-compose up -d

script:
  - sleep 2  # Wait for api to be up
  - docker-compose exec app nosetests app/test -vv
  - docker-compose exec app casperjs test app/test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
    -in client-secret.json.enc -out client-secret.json -d
  - version=$(if [ ! -z "$TRAVIS_TAG" ]; then echo $(cut -d'-' -f2 <<<"$TRAVIS_TAG"); else echo "$TRAVIS_BRANCH"; fi)
  - echo "Version = $version"
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: sympy-gamma-hrd
  skip_cleanup: true
  no_promote: true
  version: "$version"
  on:
    all_branches: true
    repo: sympy/sympy_gamma

after_deploy:
  - pip install requests
  - python bin/update_status_on_pr.py
