runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always

- url: /google5acf6d2992c8237d.html
  static_files: google5acf6d2992c8237d.html
  upload: google5acf6d2992c8237d.html
  secure: always

- url: /static
  static_dir: static/

- url: /.*
  script: auto
  secure: always

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "client-secret.json"
  PROJECT_ID: "sympy-gamma-hrd"
